on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt  # assuming you have a requirements.txt file

      - name: Run tests
        run: pytest tests/test.py  

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t manasaivaturi/pomodoro:actions .

      - name: Push Docker image to Docker Hub
        run: docker push manasaivaturi/pomodoro:actions